### ISSUE TITLE
135M 모델은 오픈계획이 없으신가요?

### ISSUE THREAD

**Issue by rippertnt** [kakaobrain/kogpt#1]
안녕하세요. 커뮤니티 보고 찾아서 들어왔습니다.
우선 내부 연구중인 결과물을 많은 사람들이 활용할 수 있게 오픈해 주심에 감사드립니다.

다름이 아니라 RTX A6000 이 있어서 다행히도 32GB 최소 사양에는 만족하나,
실생활 레벨에서 쓰려고 하면 좀더 작은 파라메터의 모델이 효과적일 것 같습니다.

벤치마크 올리신걸 보니 135M 모델이 있고, 6B 모델에 근접한 성능인 것 같은데
135M 모델은 오픈하실 계획이 없으신지 하여 문의드립니다.

**Comment by wbaek** [comment]
@rippertnt 안녕하세요.
이번에 공개한  6B 모델 말고도 다양한 모델을 가지고 있고, 더 좋은 성능의 모델을 공개하기 위해 준비하고 있습니다.

성능 평가의 경우 downstream task 평가 절차에 따라 평가 되었지만 실제 GPT모델의 생성능력이 평가된것은 아니기는 합니다.
따라서 6B보다 작은 모델의 경우는 저희 내부적으로 테스트가 많이 이루어지지 않아 좀더 확인 절차가 필요하기는 합니다.
최고 수준의 모델 뿐만아니라 실제 황용할 수 있는 수준의 모델 공개도 함께 검토해보고, 공개 가능한 시점에 다시 노티 드리겠습니다.

감사합니다.
