### ISSUE TITLE
mac m1에서  cpu 실행시 half() 오류

### ISSUE THREAD

**Issue by dharana77** [kakaobrain/kogpt#15]
https://github.com/kakaobrain/pororo/issues/11 처럼

m1에서 cpu로 실행시 추론 단계에서 문장을 입력하면
RuntimeError: "LayerNormKernelImpl" not implemented for 'Half' 오류가 뜨는 것 같습니다.

**Comment by wbaek** [comment]
kogpt 프로젝트는 공식적으로 m1하드웨어를 지원하지 않기 때문에 따로 동작이나 알고리즘상의 동작의 정밀성을 보장하지는 않습니다.
하지만 단순 half precison이슈 라고 판단되시면
revison을 float16을 제거해서 시도해보시는 것도 방법일 수 있습니다
`revision='KoGPT6B-ryan1.5b'`
