### ISSUE TITLE
gpu 메모리 관련

### ISSUE THREAD

**Issue by fmlini251** [kakaobrain/kogpt#19]
안녕하세요. 혹시 학습에 사용된 gpu 총 메모리를 알 수 있을까요?
Finetuning을 진행하고 싶은데 40gb A100 *4로는 OOM이 발생하는 것 같습니다.

**Comment by nomorecoke** [comment]
저도 같은 궁금증이 있는데요 A100에 길이 16짜리 문장도 1 batch finetuning이 불가능해보입니다.

혹시 머신 스펙이나 다른 방법으로 튜닝해야하는지 알 수 있을까요?
