### ISSUE TITLE
Finetuning Licensing 

### ISSUE THREAD

**Issue by ksjae** [kakaobrain/kogpt#2]
CC-BY-NC-ND 조건에 의하면 2차창작물 배포가 금지되어 있습니다(Pretrained Weights의 경우). 그러면 자체 데이터셋으로 Finetuning 진행 후 배포가 금지되나요?

+Tokenizer에도 동일하게 적용되는지 문의드립니다.

**Comment by wbaek** [comment]
@ksjae 기본적으로 공개된 `Pretrained Weights`전부는 `CC-BY-NC-ND`라이센스를 따르고 있습니다.
Finetune후에 생성된 weights는 2차 창작물로 판단되기 때문에 재배포가 금지됩니다.
이는 tokenizer에도 동일합니다.
tokenizer의 경우 변경이 일어나기 쉽지 않기 때문에 가급적 저희가 공개한 리파지터리내에서 활용을 부탁드립니다.

저희가 관리되지 않은 재배포의 경우 엄격히 제한하고 있지만
연구 개발과 관련된 목적으로는 [contact@kakaobrain.com](mailto://contact@kakaobrain.com) 으로 사용처나 재배포 목적등을 포함하여 문의를 주시면 검토후에 답변드리겠습니다.

감사합니다.
