### ISSUE TITLE
모델의 생성 결과물의 독성(Toxicity)에 관하여

### ISSUE THREAD

**Issue by combacsa** [kakaobrain/kogpt#5]
안녕하세요, KoGPT 모델의 놀라운 성능을 확인하고, 두 가지 제안을 드리고 싶은 것이 있어 issue 를 열게 되었습니다.

현재 README.md 에서는 아래와 같이 영문으로 모델의 생성 결과물이 충분히 독성을 띨 수 있음을 명시하고 계신 것으로 보입니다.

```
KakaoBrain KoGPT was trained on rayn dataset, a dataset known to contain profanity, lewd, political changed, and other harsh language. Therefore, KoGPT can generate socially unacceptable texts. As with all language models, It is difficult to predict in advance how KoGPT will response to particular prompts and offensive content without warning.
```

두 가지 제안을 드리고 싶습니다.

(1) License 에 대해서는 한국어로도 병기해 주신 것처럼, Limitations 에 대해서도 한국어로 병기해 주시면 어떨지 제안드립니다. 여지껏 공개된 모델 중 가장 강력한 성능을 지닌 것으로 보이고, 그만큼 모델 활용 과정에서 마주칠 수 있는 여러 위험한 상황에 대해 한국어 화자들이 좀더 인지할 수 있도록, 한국어로도 명시해 주실 수 있을지요?

(2) 모델에 대한 [if kakao 영상](https://if.kakao.com/session/48)에서 모델 활용 과정에서 발생할 수 있는 여러 가지 윤리적 위험성에 대해 말씀해주시는 지점이 있었습니다. 몇 가지 특수한 `prompt`로 KoGPT를 사용해 보니 (제 주관적으로 느끼기에) 상당히 높은 수위의 `offensive content`를 생성해내는 것을 보면서 다소 염려가 됩니다. 전례를 알지 못하여 구체적인 제안을 드리기 좀 어렵지만, `contact@kakaobrain.com` 이외에, 공개하신 모델의 독성(Toxicity)이 특히 잘 드러나는 `prompt`들에 관한 정보를 사후적으로라도 수집/연구/정제를 하는 창구를 별도로 열어주시는 것이 가능하실지요?

**Comment by wbaek** [comment]
@combacsa 우려해 주신 부분에 대해서 저희도 크게 공감하고 있습니다.

제안주신 두가지 중에서 첫번째는 한계점에 대한 한국어 병기는 바로 반영하도록 하겠습니다.

그리고 두번째로 제안주신 문제의 케이스를 수집하는 건의 경우도 빠른 시일내에 수집할 수 있는 창구를 준비해 제보하실 수 있도록 준비해 보겠습니다.
수집된 문제의 상황에 대해서는 내부에서 검토를 거쳐 장기적으로 연구 개발에 도움이 될 수 있게 정제하여 공개하는 방안도 함께 고민해보겠습니다.

감사합니다.

**Comment by wbaek** [comment]
문제의 케이스를 수집하는 건이 정리되기 전까지 이슈는 오픈해 놓겠습니다.

**Comment by wbaek** [comment]
@combacsa opensource+kogpt@kakaobrain.com로 "prompt"와 "생성된 문장"을 함께 보내주시면 됩니다. 감사합니다. :D

**Comment by combacsa** [comment]
고맙습니다. 오늘 처음으로 한 차례 prompt 와 생성문장들을 정리하여 보내드렸습니다. 개인적인 시간에 취미로 확인하는 것이다보니 동일 prompt 로 동일하게 재현이 될지는 잘 모르겠습니다. 모쪼록 메일로 보내드린 정보가 모델의 오용을 막는 과정에 보탬이 되길 바랍니다.
