### ISSUE TITLE
 텍스트를 분류, 검색, 요약 코드에 대한 간단한 예제 코드 혹시 업로드 가능하실까요!?

### ISSUE THREAD

**Issue by Aramir-A1DATAINT** [kakaobrain/kogpt#8]
안녕하세요!!
딥러닝을 열심히 배우고 있는 학생입니다..!

README에 생성 코드는 너무 상세하게 작성되어 있어서... 너무 잘 구현해 봤습니다.!

README를 쭉 일어 보니 모델이 텍스트 분류 요약 검색에 대해 특화가 되어 있다고 하는데...
예제 코드를 보고 공부를 하고 싶은데 .. 어떻게 해야 할지 감이 안 잡혀서 염치 불구하고 이슈 올려봅니다!!

멋진 모델을 공개해주신 카카오 브래인 분들에게 감사를 표하며!!

**Comment by wbaek** [comment]
실제로 GPT를 잘 활용하기 위해서는 프롬프트를 디자인 하는 것이 중요한 문제이기는 합니다.
기본적인 방법론이나 활용등은 기 발표된 논문을 통해 찾아 보실 수 있습니다.

저희가 공개한 KoGPT기반의 응용 github page에서 몇가지 예제를 찾아 보실 수도 있습니다.
https://github.com/DeepSE/gpt_playground

해당 프로젝트에 몇가지 예제를 남겨놓았습니다.
한줄요약: https://github.com/DeepSE/gpt_playground/issues/76
긍부정: https://github.com/DeepSE/gpt_playground/issues/73
질의응답: https://github.com/DeepSE/gpt_playground/issues/74
질의응답: https://github.com/DeepSE/gpt_playground/issues/75

**Comment by purang2** [comment]
안녕하세요 !! 

저는 kakaobrain과는 무관하고 [KNU-BrainAI 연구실](https://github.com/KNU-BrainAI)에서 자연어처리 등을 공부하고 있는 석사과정 대학원생 ([purang2](https://github.com/purang2))입니다. 😁 

다름이 아니라 저희 연구실에서 공부하고 있는 GPT 관련 레포시토리의 KoGPT 파트를 직접 제작하며 저희들끼리 스터디그룹 활동을 진행하고 있는데, 

KoGPT라는 너무 흥미로운 주제에 대해 이것저것 찾아보다가 이 글을 보게 되었고, 

혹시나마 저희의 저장소를 공유하면 조금이나마 도움이 되실까봐 여기 Issue에 댓글과 링크 남기고 갑니다!

석사과정 학생들이 만들기 때문에 수준적으로 높진 않겠지만 매주 계속 업로드 될 예정이니 누구든지 자유롭게 봐주시면 감사하겠습니다!!

아래는 저희 Repository 주소입니다. 

https://github.com/purang2/GPT/tree/main/BrainAILab-NLP-Study/kakaobrain-KoGPT


행복한 하루 되세요!😁😁
